GET http://local.audryus.com:9200/ HTTP/1.1
Content-Type: application/json
###
PUT http://local.audryus.com:9200/items HTTP/1.1
Content-Type: application/json

{
    "settings": {
        "index": {
            "number_of_shards": 4,
            "number_of_replicas": 2
        }
    }
}
###
GET http://local.audryus.com:9200/items HTTP/1.1
Content-Type: application/json


###
GET http://local.audryus.com:9200/items/_search HTTP/1.1
Content-Type: application/json

###
GET http://local.audryus.com:9200/_nodes/http?pretty HTTP/1.1
Content-Type: application/json

