GET http://127.0.0.1:8082/ping HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:8082/items?token=97e0fbb9999661d5bcba7d55ad4cd872 HTTP/1.1
Content-Type: application/json

{
    "title": "this is the title",
    "description": {
        "plain_text": "text description"
    },
    "status": "pending",
    "available_quantity": 10
}
###
GET http://local.audryus.com:9200/items/_search HTTP/1.1
Content-Type: application/json
